create table WatermarkedDocument (
    id bigint generated by default as identity,
    content varchar(10) not null,
    topic varchar(255),
    title varchar(255) not null,
    author varchar(255) not null,
    isWatermarked boolean not null,
    primary key (id),
    unique (content, title, author, topic)
);